# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Authors:
# - Paul Scheffler <paulsc@iis.ee.ethz.ch>
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

name: gitlab-ci

on:
  push:
    branches-ignore:
      - '__deploy__**'
  pull_request:
    branches-ignore:
      - '__deploy__**'
  workflow_dispatch:
    branches-ignore:
      - '__deploy__**'

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Mirror and check
        uses: pulp-platform/pulp-actions/gitlab-ci@v2
        # Skip on forks or pull requests from forks due to missing secrets.
        if: >
          github.repository == 'pulp-platform/idma' &&
          (github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository)
        with:
          domain: iis-git.ee.ethz.ch
          repo: github-mirror/idma
          token: ${{ secrets.GITLAB_TOKEN }}
          poll-count: 10800 # (10800/60=180min=3hours)

  check-verilator:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
      -
        name: Install Python requirements
        run: pip install -r requirements.txt
      -
        name: Install Bender
        uses: pulp-platform/pulp-actions/bender-install@v2
        with:
          version: 0.27.3
      -
        name: Install Morty
        run: |
          curl --proto '=https' --tlsv1.2 -sLO https://github.com/pulp-platform/morty/releases/download/v0.9.0/morty-ubuntu.22.04-x86_64.tar.gz
          tar -xvf morty-ubuntu.22.04-x86_64.tar.gz morty
          rm -f morty-ubuntu.22.04-x86_64.tar.gz
          chmod 777 morty
          echo "PATH=.:$PATH" >> ${GITHUB_ENV}
      -
        name: Install verilator
        run: |
          git clone -b nba-enable-initial-final https://github.com/RootCubed/verilator.git ~/verilator
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install
      -
        name: Build sim
        run: make idma_sim_all
      -
        name: Run simulation
        run:
          cd test/backend
          ./idma.sh
          ./obj_dir/tb_idma ../../jobs/backend_r_axi_w_obi/simple.yml
